### PR TITLE
makes FRAMEWORK_SEARCH_PATHS recursive

### PR DESCRIPTION
**Pull request by dipidoo**

### CODE REVIEW

**Comment by msaps** [comment]
@dipidoo this doesn't seem to resolve anything? Am I missing something? 😅

**Comment by msaps** [comment]
@dipidoo ah interestingly - I just tried making `Framework Search Paths` recursive for both the Framework target and App target and it seemed to fix it...

**Comment by dipidoo** [comment]
I see, I updated the PR to reflect that. Please accept the answer at SO when you have a chance: https://stackoverflow.com/questions/60078417 thank you.

**Comment by msaps** [comment]
@dipidoo I've tried this as a workaround in multiple projects, some it seems to work fine and others have issues finding the correct architecture `.framework` and the build still fails. So mileage may vary with this. 

An article was recently posted by [pyckamil](https://github.com/pyckamil) - [Everything wrong with XCFrameworks](https://pyckamil.github.io/programming,/xcframework,/xcode/2020/05/09/everything-wrong-with-xcframeworks.html). He found the exact reason that causes this problem (and it boils down to an Xcode optimisation that only extracts the `.framework` from an `.xcframework` once, causing additional targets to have potentially have issues).

I've documented it in the README and will also update the SO post with this info 👍

**Pull request closed without merging**
